import type { InsertState, InsertCity, InsertRace, InsertRaceOccurrence, InsertRoute, InsertSource, InsertCollection } from "@shared/schema";
import { storage } from "./storage";
import { db } from "./db";
import { states, races, cities } from "@shared/schema";
import { eq } from "drizzle-orm";

const SEED_STATES: InsertState[] = [
  { name: "Alabama", slug: "alabama", abbreviation: "AL", raceCount: 65, routeCount: 120, popularCities: ["Birmingham", "Huntsville", "Mobile"] },
  { name: "Alaska", slug: "alaska", abbreviation: "AK", raceCount: 25, routeCount: 80, popularCities: ["Anchorage", "Fairbanks", "Juneau"] },
  { name: "Arizona", slug: "arizona", abbreviation: "AZ", raceCount: 110, routeCount: 200, popularCities: ["Phoenix", "Tucson", "Scottsdale", "Sedona"] },
  { name: "Arkansas", slug: "arkansas", abbreviation: "AR", raceCount: 45, routeCount: 90, popularCities: ["Little Rock", "Fayetteville", "Hot Springs"] },
  { name: "California", slug: "california", abbreviation: "CA", raceCount: 450, routeCount: 1200, popularCities: ["San Francisco", "Los Angeles", "San Diego", "Sacramento"] },
  { name: "Colorado", slug: "colorado", abbreviation: "CO", raceCount: 190, routeCount: 950, popularCities: ["Denver", "Boulder", "Colorado Springs", "Fort Collins"] },
  { name: "Connecticut", slug: "connecticut", abbreviation: "CT", raceCount: 80, routeCount: 150, popularCities: ["Hartford", "New Haven", "Stamford"] },
  { name: "Delaware", slug: "delaware", abbreviation: "DE", raceCount: 30, routeCount: 60, popularCities: ["Wilmington", "Dover", "Newark"] },
  { name: "Florida", slug: "florida", abbreviation: "FL", raceCount: 240, routeCount: 450, popularCities: ["Miami", "Orlando", "Tampa", "Jacksonville"] },
  { name: "Georgia", slug: "georgia", abbreviation: "GA", raceCount: 140, routeCount: 280, popularCities: ["Atlanta", "Savannah", "Augusta"] },
  { name: "Hawaii", slug: "hawaii", abbreviation: "HI", raceCount: 50, routeCount: 120, popularCities: ["Honolulu", "Maui", "Kona"] },
  { name: "Idaho", slug: "idaho", abbreviation: "ID", raceCount: 40, routeCount: 180, popularCities: ["Boise", "Sun Valley", "Coeur d'Alene"] },
  { name: "Illinois", slug: "illinois", abbreviation: "IL", raceCount: 180, routeCount: 350, popularCities: ["Chicago", "Naperville", "Springfield"] },
  { name: "Indiana", slug: "indiana", abbreviation: "IN", raceCount: 90, routeCount: 160, popularCities: ["Indianapolis", "Fort Wayne", "Bloomington"] },
  { name: "Iowa", slug: "iowa", abbreviation: "IA", raceCount: 55, routeCount: 100, popularCities: ["Des Moines", "Iowa City", "Cedar Rapids"] },
  { name: "Kansas", slug: "kansas", abbreviation: "KS", raceCount: 50, routeCount: 80, popularCities: ["Kansas City", "Wichita", "Lawrence"] },
  { name: "Kentucky", slug: "kentucky", abbreviation: "KY", raceCount: 60, routeCount: 140, popularCities: ["Louisville", "Lexington", "Bowling Green"] },
  { name: "Louisiana", slug: "louisiana", abbreviation: "LA", raceCount: 55, routeCount: 90, popularCities: ["New Orleans", "Baton Rouge", "Lafayette"] },
  { name: "Maine", slug: "maine", abbreviation: "ME", raceCount: 65, routeCount: 180, popularCities: ["Portland", "Bar Harbor", "Bangor"] },
  { name: "Maryland", slug: "maryland", abbreviation: "MD", raceCount: 110, routeCount: 200, popularCities: ["Baltimore", "Annapolis", "Bethesda"] },
  { name: "Massachusetts", slug: "massachusetts", abbreviation: "MA", raceCount: 150, routeCount: 400, popularCities: ["Boston", "Cambridge", "Worcester"] },
  { name: "Michigan", slug: "michigan", abbreviation: "MI", raceCount: 120, routeCount: 280, popularCities: ["Detroit", "Ann Arbor", "Grand Rapids", "Traverse City"] },
  { name: "Minnesota", slug: "minnesota", abbreviation: "MN", raceCount: 110, routeCount: 250, popularCities: ["Minneapolis", "St. Paul", "Duluth"] },
  { name: "Mississippi", slug: "mississippi", abbreviation: "MS", raceCount: 35, routeCount: 60, popularCities: ["Jackson", "Hattiesburg", "Oxford"] },
  { name: "Missouri", slug: "missouri", abbreviation: "MO", raceCount: 85, routeCount: 160, popularCities: ["St. Louis", "Kansas City", "Columbia"] },
  { name: "Montana", slug: "montana", abbreviation: "MT", raceCount: 45, routeCount: 200, popularCities: ["Missoula", "Bozeman", "Billings"] },
  { name: "Nebraska", slug: "nebraska", abbreviation: "NE", raceCount: 45, routeCount: 80, popularCities: ["Omaha", "Lincoln"] },
  { name: "Nevada", slug: "nevada", abbreviation: "NV", raceCount: 55, routeCount: 120, popularCities: ["Las Vegas", "Reno", "Henderson"] },
  { name: "New Hampshire", slug: "new-hampshire", abbreviation: "NH", raceCount: 60, routeCount: 200, popularCities: ["Manchester", "Concord", "Portsmouth"] },
  { name: "New Jersey", slug: "new-jersey", abbreviation: "NJ", raceCount: 130, routeCount: 220, popularCities: ["Newark", "Jersey City", "Princeton"] },
  { name: "New Mexico", slug: "new-mexico", abbreviation: "NM", raceCount: 50, routeCount: 150, popularCities: ["Albuquerque", "Santa Fe", "Las Cruces"] },
  { name: "New York", slug: "new-york", abbreviation: "NY", raceCount: 320, routeCount: 800, popularCities: ["New York City", "Albany", "Buffalo", "Syracuse"] },
  { name: "North Carolina", slug: "north-carolina", abbreviation: "NC", raceCount: 140, routeCount: 350, popularCities: ["Charlotte", "Raleigh", "Asheville"] },
  { name: "North Dakota", slug: "north-dakota", abbreviation: "ND", raceCount: 20, routeCount: 40, popularCities: ["Fargo", "Bismarck"] },
  { name: "Ohio", slug: "ohio", abbreviation: "OH", raceCount: 130, routeCount: 250, popularCities: ["Columbus", "Cleveland", "Cincinnati"] },
  { name: "Oklahoma", slug: "oklahoma", abbreviation: "OK", raceCount: 55, routeCount: 100, popularCities: ["Oklahoma City", "Tulsa", "Norman"] },
  { name: "Oregon", slug: "oregon", abbreviation: "OR", raceCount: 130, routeCount: 550, popularCities: ["Portland", "Eugene", "Bend"] },
  { name: "Pennsylvania", slug: "pennsylvania", abbreviation: "PA", raceCount: 160, routeCount: 300, popularCities: ["Philadelphia", "Pittsburgh", "Lancaster"] },
  { name: "Rhode Island", slug: "rhode-island", abbreviation: "RI", raceCount: 35, routeCount: 70, popularCities: ["Providence", "Newport"] },
  { name: "South Carolina", slug: "south-carolina", abbreviation: "SC", raceCount: 75, routeCount: 140, popularCities: ["Charleston", "Columbia", "Greenville"] },
  { name: "South Dakota", slug: "south-dakota", abbreviation: "SD", raceCount: 25, routeCount: 60, popularCities: ["Sioux Falls", "Rapid City"] },
  { name: "Tennessee", slug: "tennessee", abbreviation: "TN", raceCount: 110, routeCount: 250, popularCities: ["Nashville", "Memphis", "Knoxville", "Chattanooga"] },
  { name: "Texas", slug: "texas", abbreviation: "TX", raceCount: 280, routeCount: 600, popularCities: ["Austin", "Houston", "Dallas", "San Antonio"] },
  { name: "Utah", slug: "utah", abbreviation: "UT", raceCount: 100, routeCount: 400, popularCities: ["Salt Lake City", "Park City", "St. George", "Moab"] },
  { name: "Vermont", slug: "vermont", abbreviation: "VT", raceCount: 45, routeCount: 160, popularCities: ["Burlington", "Montpelier", "Stowe"] },
  { name: "Virginia", slug: "virginia", abbreviation: "VA", raceCount: 150, routeCount: 320, popularCities: ["Arlington", "Richmond", "Virginia Beach", "Charlottesville"] },
  { name: "Washington", slug: "washington", abbreviation: "WA", raceCount: 160, routeCount: 500, popularCities: ["Seattle", "Tacoma", "Spokane", "Bellingham"] },
  { name: "West Virginia", slug: "west-virginia", abbreviation: "WV", raceCount: 30, routeCount: 120, popularCities: ["Charleston", "Morgantown"] },
  { name: "Wisconsin", slug: "wisconsin", abbreviation: "WI", raceCount: 100, routeCount: 200, popularCities: ["Milwaukee", "Madison", "Green Bay"] },
  { name: "Wyoming", slug: "wyoming", abbreviation: "WY", raceCount: 20, routeCount: 100, popularCities: ["Jackson", "Cheyenne", "Cody"] },
];

const SEED_RACES: InsertRace[] = [
  // === WORLD MARATHON MAJORS (US) ===
  { slug: "boston-marathon", name: "Boston Marathon", date: "2025-04-21", city: "Boston", state: "MA", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "The world's oldest annual marathon. From Hopkinton to Boylston Street, this iconic point-to-point course tests the best.", website: "https://www.baa.org/races/boston-marathon", registrationUrl: "https://www.baa.org/races/boston-marathon/enter", startTime: "10:00 AM", timeLimit: "6 hours", bostonQualifier: false, distanceLabel: "Marathon", distanceMeters: 42195, lat: 42.3601, lng: -71.0589, qualityScore: 95 },
  { slug: "nyc-marathon", name: "TCS New York City Marathon", date: "2025-11-02", city: "New York City", state: "NY", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "The world's largest marathon, traversing all five boroughs of New York City with an electric finish in Central Park.", website: "https://www.nyrr.org/tcsnycmarathon", registrationUrl: "https://www.nyrr.org/tcsnycmarathon/runners/apply", startTime: "9:10 AM", timeLimit: "8.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 40.7128, lng: -74.0060, qualityScore: 95 },
  { slug: "chicago-marathon", name: "Bank of America Chicago Marathon", date: "2025-10-12", city: "Chicago", state: "IL", distance: "Marathon", surface: "Road", elevation: "Flat", description: "One of the World Marathon Majors, this flat and fast course winds through 29 Chicago neighborhoods.", website: "https://www.chicagomarathon.com", registrationUrl: "https://www.chicagomarathon.com/runners/application-process/", startTime: "7:30 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 41.8781, lng: -87.6298, qualityScore: 95 },

  // === MAJOR US MARATHONS ===
  { slug: "la-marathon", name: "Los Angeles Marathon", date: "2025-03-09", city: "Los Angeles", state: "CA", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "A stadium-to-the-sea course from Dodger Stadium to Santa Monica, passing through iconic LA neighborhoods and landmarks.", website: "https://www.lamarathon.com", registrationUrl: "https://www.lamarathon.com/register", startTime: "6:30 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 34.0522, lng: -118.2437, qualityScore: 88 },
  { slug: "sf-marathon", name: "The San Francisco Marathon", date: "2025-07-27", city: "San Francisco", state: "CA", distance: "Marathon", surface: "Road", elevation: "Hilly", description: "Run through the iconic streets of San Francisco, crossing the Golden Gate Bridge and winding through diverse neighborhoods.", website: "https://www.thesfmarathon.com", registrationUrl: "https://www.thesfmarathon.com/register/", startTime: "5:30 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 37.7749, lng: -122.4194, qualityScore: 85 },
  { slug: "marine-corps-marathon", name: "Marine Corps Marathon", date: "2025-10-26", city: "Arlington", state: "VA", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "Known as 'The People's Marathon,' this race passes DC's most iconic monuments and memorials.", website: "https://www.marinemarathon.com", registrationUrl: "https://www.marinemarathon.com/events/marathon", startTime: "7:55 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 38.8816, lng: -77.0910, qualityScore: 90 },
  { slug: "twin-cities-marathon", name: "Medtronic Twin Cities Marathon", date: "2025-10-05", city: "Minneapolis", state: "MN", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "Known as 'The Most Beautiful Urban Marathon in America,' connecting Minneapolis and St. Paul along tree-lined lakes.", website: "https://www.tcmevents.org", registrationUrl: "https://www.tcmevents.org/events/medtronic_twin_cities_marathon", startTime: "8:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 44.9778, lng: -93.2650, qualityScore: 87 },
  { slug: "grandmas-marathon", name: "Grandma's Marathon", date: "2025-06-21", city: "Duluth", state: "MN", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "A scenic point-to-point course along Lake Superior's North Shore, finishing in Canal Park, Duluth.", website: "https://www.grandmasmarathon.com", registrationUrl: "https://www.grandmasmarathon.com/the-races/grandmas-marathon/", startTime: "7:30 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 46.7867, lng: -92.1005, qualityScore: 86 },
  { slug: "st-george-marathon", name: "St. George Marathon", date: "2025-10-04", city: "St. George", state: "UT", distance: "Marathon", surface: "Road", elevation: "Downhill", description: "A fast, net-downhill course through stunning red rock country in southern Utah. One of the top BQ courses.", website: "https://www.stgeorgemarathon.com", registrationUrl: "https://www.stgeorgemarathon.com/runners/registration/", startTime: "6:45 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 37.0965, lng: -113.5684, qualityScore: 88 },
  { slug: "cim-marathon", name: "California International Marathon", date: "2025-12-07", city: "Sacramento", state: "CA", distance: "Marathon", surface: "Road", elevation: "Downhill", description: "A fast, net-downhill point-to-point course from Folsom to the State Capitol. One of the premier BQ courses in the US.", website: "https://runsra.org/california-international-marathon/", registrationUrl: "https://runsra.org/california-international-marathon/registration/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 38.5816, lng: -121.4944, qualityScore: 88 },
  { slug: "philadelphia-marathon", name: "Philadelphia Marathon", date: "2025-11-23", city: "Philadelphia", state: "PA", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A fast, flat course past historic landmarks including Independence Hall, the Art Museum, and Boathouse Row.", website: "https://www.philadelphiamarathon.com", registrationUrl: "https://www.philadelphiamarathon.com/register/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 39.9526, lng: -75.1652, qualityScore: 86 },
  { slug: "houston-marathon", name: "Chevron Houston Marathon", date: "2025-01-19", city: "Houston", state: "TX", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A fast, flat course through Houston that regularly produces qualifying times and personal records.", website: "https://www.chevronhoustonmarathon.com", registrationUrl: "https://www.chevronhoustonmarathon.com/register/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 29.7604, lng: -95.3698, qualityScore: 87 },
  { slug: "austin-marathon", name: "Austin Marathon", date: "2025-02-16", city: "Austin", state: "TX", distance: "Marathon", surface: "Road", elevation: "Hilly", description: "Experience Austin's vibrant culture and live music along this challenging course through the Texas capital.", website: "https://youraustinmarathon.com", registrationUrl: "https://youraustinmarathon.com/register/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 30.2672, lng: -97.7431, qualityScore: 82 },
  { slug: "miami-marathon", name: "Life Time Miami Marathon", date: "2025-02-02", city: "Miami", state: "FL", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A flat, fast course through Miami's most scenic neighborhoods with ocean views along the Venetian Causeway.", website: "https://www.themiamimarathon.com", registrationUrl: "https://www.themiamimarathon.com/register/", startTime: "6:00 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 25.7617, lng: -80.1918, qualityScore: 85 },
  { slug: "big-sur-marathon", name: "Big Sur International Marathon", date: "2025-04-27", city: "Big Sur", state: "CA", distance: "Marathon", surface: "Road", elevation: "Hilly", description: "Consistently rated the most scenic marathon in the world, running along Highway 1 with stunning Pacific Ocean views.", website: "https://www.bigsurmarathon.org", registrationUrl: "https://www.bigsurmarathon.org/registration/", startTime: "6:45 AM", timeLimit: "6 hours", bostonQualifier: false, distanceLabel: "Marathon", distanceMeters: 42195, lat: 36.2704, lng: -121.8081, qualityScore: 90 },
  { slug: "honolulu-marathon", name: "Honolulu Marathon", date: "2025-12-14", city: "Honolulu", state: "HI", distance: "Marathon", surface: "Road", elevation: "Flat", description: "One of the largest marathons in the world with no time limit. Run from Ala Moana to Hawaii Kai and back with Diamond Head views.", website: "https://www.honolulumarathon.org", registrationUrl: "https://www.honolulumarathon.org/registration", startTime: "5:00 AM", timeLimit: "None", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 21.3069, lng: -157.8583, qualityScore: 88 },
  { slug: "detroit-marathon", name: "Detroit Free Press Marathon", date: "2025-10-19", city: "Detroit", state: "MI", distance: "Marathon", surface: "Road", elevation: "Flat", description: "The only marathon to cross an international border, running through the Detroit-Windsor Tunnel to Canada and back.", website: "https://www.freepmarathon.com", registrationUrl: "https://www.freepmarathon.com/register/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 42.3314, lng: -83.0458, qualityScore: 82 },
  { slug: "portland-marathon", name: "Portland Marathon", date: "2025-10-05", city: "Portland", state: "OR", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A scenic tour of Portland crossing multiple bridges and running along the Willamette River waterfront.", website: "https://www.portlandmarathon.com", registrationUrl: "https://www.portlandmarathon.com/register/", startTime: "7:00 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 45.5152, lng: -122.6784, qualityScore: 80 },
  { slug: "seattle-marathon", name: "Seattle Marathon", date: "2025-11-30", city: "Seattle", state: "WA", distance: "Marathon", surface: "Road", elevation: "Hilly", description: "Run through the Emerald City's iconic neighborhoods, past the Space Needle, and along the shores of Lake Washington.", website: "https://www.seattlemarathon.org", registrationUrl: "https://www.seattlemarathon.org/registration/", startTime: "7:00 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 47.6062, lng: -122.3321, qualityScore: 80 },
  { slug: "richmond-marathon", name: "Richmond Marathon", date: "2025-11-15", city: "Richmond", state: "VA", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "A scenic course through Virginia's capital city, passing historic monuments, the James River, and charming neighborhoods.", website: "https://www.richmondmarathon.org", registrationUrl: "https://www.richmondmarathon.org/register/", startTime: "8:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 37.5407, lng: -77.4360, qualityScore: 82 },
  { slug: "erie-marathon", name: "Erie Marathon at Presque Isle", date: "2025-09-14", city: "Erie", state: "PA", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A fast, flat BQ-friendly course around beautiful Presque Isle State Park along the shores of Lake Erie.", website: "https://www.eriemarathon.com", registrationUrl: "https://www.eriemarathon.com/register/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 42.1292, lng: -80.0851, qualityScore: 78 },
  { slug: "indianapolis-marathon", name: "CNO Financial Indianapolis Monumental Marathon", date: "2025-11-08", city: "Indianapolis", state: "IN", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A fast, flat course through downtown Indianapolis past iconic monuments and memorials. Popular BQ course.", website: "https://www.monumentalmarathon.com", registrationUrl: "https://www.monumentalmarathon.com/races/marathon/", startTime: "8:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 39.7684, lng: -86.1581, qualityScore: 83 },
  { slug: "columbus-marathon", name: "Nationwide Children's Hospital Columbus Marathon", date: "2025-10-19", city: "Columbus", state: "OH", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A flat, fast course through Ohio's capital that is consistently rated one of the best BQ courses in the country.", website: "https://www.columbusmarathon.com", registrationUrl: "https://www.columbusmarathon.com/register/", startTime: "7:30 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 39.9612, lng: -82.9988, qualityScore: 83 },
  { slug: "revel-mt-charleston", name: "REVEL Mt Charleston Marathon", date: "2025-04-12", city: "Las Vegas", state: "NV", distance: "Marathon", surface: "Road", elevation: "Downhill", description: "A net-downhill course descending over 5,200 feet from Mt. Charleston to the Las Vegas valley. Ultra-fast BQ course.", website: "https://www.runrevel.com/rmc", registrationUrl: "https://www.runrevel.com/rmc/register", startTime: "6:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 36.1699, lng: -115.1398, qualityScore: 82 },
  { slug: "new-orleans-marathon", name: "Humana Rock 'n' Roll New Orleans Marathon", date: "2025-02-09", city: "New Orleans", state: "LA", distance: "Marathon", surface: "Road", elevation: "Flat", description: "Run through the heart of the Big Easy, past the French Quarter, Garden District, and along the shores of Lake Pontchartrain.", website: "https://www.runrocknroll.com/new-orleans", registrationUrl: "https://www.runrocknroll.com/new-orleans", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 29.9511, lng: -90.0715, qualityScore: 82 },
  { slug: "missoula-marathon", name: "Missoula Marathon", date: "2025-06-29", city: "Missoula", state: "MT", distance: "Marathon", surface: "Road", elevation: "Downhill", description: "A net-downhill point-to-point course through Montana's beautiful Bitterroot Valley, finishing in downtown Missoula.", website: "https://www.missoulamarathon.org", registrationUrl: "https://www.missoulamarathon.org/register/", startTime: "6:00 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 46.8721, lng: -113.9940, qualityScore: 80 },
  { slug: "jacksonville-marathon", name: "Gate River Run & Jacksonville Marathon", date: "2025-12-14", city: "Jacksonville", state: "FL", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A flat, fast winter marathon through Jacksonville's scenic riverfront and historic neighborhoods.", website: "https://www.1702events.com/jacksonville-marathon", registrationUrl: "https://www.1702events.com/jacksonville-marathon", startTime: "6:30 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 30.3322, lng: -81.6557, qualityScore: 75 },
  { slug: "denver-marathon", name: "Colfax Marathon", date: "2025-05-18", city: "Denver", state: "CO", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "Denver's flagship marathon runs along Colfax Avenue, through City Park, and past the State Capitol at 5,280 feet elevation.", website: "https://www.runcolfax.org", registrationUrl: "https://www.runcolfax.org/races/marathon/", startTime: "6:00 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 39.7392, lng: -104.9903, qualityScore: 80 },
  { slug: "charleston-marathon", name: "Charleston Marathon", date: "2025-01-11", city: "Charleston", state: "SC", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A flat, fast winter course through historic Charleston, passing antebellum homes and the beautiful waterfront.", website: "https://www.charlestonmarathon.com", registrationUrl: "https://www.charlestonmarathon.com/registration/", startTime: "7:30 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 32.7765, lng: -79.9311, qualityScore: 78 },

  // === HALF MARATHONS ===
  { slug: "brooklyn-half", name: "RBC Brooklyn Half", date: "2025-05-17", city: "New York City", state: "NY", distance: "Half Marathon", surface: "Road", elevation: "Flat", description: "America's largest half marathon, running from Prospect Park through the streets of Brooklyn to the Coney Island boardwalk.", website: "https://www.nyrr.org/races/rbcbrooklynhalf", registrationUrl: "https://www.nyrr.org/races/rbcbrooklynhalf", startTime: "7:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 40.6782, lng: -73.9442, qualityScore: 88 },
  { slug: "rock-n-roll-las-vegas", name: "Rock 'n' Roll Las Vegas Half Marathon", date: "2025-02-23", city: "Las Vegas", state: "NV", distance: "Half Marathon", surface: "Road", elevation: "Flat", description: "The only race on the Las Vegas Strip at night. Run under the neon lights with live entertainment at every mile.", website: "https://www.runrocknroll.com/las-vegas", registrationUrl: "https://www.runrocknroll.com/las-vegas", startTime: "4:30 PM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 36.1699, lng: -115.1398, qualityScore: 85 },
  { slug: "rock-n-roll-san-diego", name: "Rock 'n' Roll San Diego Half Marathon", date: "2025-06-01", city: "San Diego", state: "CA", distance: "Half Marathon", surface: "Road", elevation: "Rolling", description: "San Diego's premier half marathon featuring live bands, cheerleaders, and a finish line festival in Balboa Park.", website: "https://www.runrocknroll.com/san-diego", registrationUrl: "https://www.runrocknroll.com/san-diego", startTime: "6:15 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 32.7157, lng: -117.1611, qualityScore: 83 },
  { slug: "rock-n-roll-nashville", name: "Rock 'n' Roll Nashville Half Marathon", date: "2025-04-26", city: "Nashville", state: "TN", distance: "Half Marathon", surface: "Road", elevation: "Hilly", description: "Run through Music City past honky-tonks, the Grand Ole Opry, and iconic Nashville landmarks with live music at every mile.", website: "https://www.runrocknroll.com/nashville", registrationUrl: "https://www.runrocknroll.com/nashville", startTime: "7:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 36.1627, lng: -86.7816, qualityScore: 83 },
  { slug: "nyc-half-marathon", name: "United Airlines NYC Half", date: "2025-03-16", city: "New York City", state: "NY", distance: "Half Marathon", surface: "Road", elevation: "Rolling", description: "From Brooklyn to Manhattan, this half marathon finishes in Central Park, passing through Times Square.", website: "https://www.nyrr.org/races/unitedairlinesnychair", registrationUrl: "https://www.nyrr.org/races/unitedairlinesnychair", startTime: "7:30 AM", timeLimit: "3.5 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 40.7128, lng: -74.0060, qualityScore: 88 },
  { slug: "rock-n-roll-dc", name: "Rock 'n' Roll Washington DC Half Marathon", date: "2025-03-15", city: "Washington", state: "DC", distance: "Half Marathon", surface: "Road", elevation: "Flat", description: "A flat course past the National Mall monuments, Capitol Building, and iconic DC landmarks with live music throughout.", website: "https://www.runrocknroll.com/washington-dc", registrationUrl: "https://www.runrocknroll.com/washington-dc", startTime: "7:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 38.9072, lng: -77.0369, qualityScore: 84 },
  { slug: "hot-chocolate-15k", name: "Hot Chocolate 15K Chicago", date: "2025-11-02", city: "Chicago", state: "IL", distance: "Other", surface: "Road", elevation: "Flat", description: "A popular fall race with chocolate-themed aid stations and a finisher's mug of hot chocolate and fondue.", website: "https://www.hotchocolate15k.com/chicago", registrationUrl: "https://www.hotchocolate15k.com/chicago", startTime: "7:00 AM", timeLimit: "3.5 hours", bostonQualifier: false, distanceLabel: "15K", distanceMeters: 15000, lat: 41.8781, lng: -87.6298, qualityScore: 75 },
  { slug: "great-race-pittsburgh", name: "Richard S. Caliguiri City of Pittsburgh Great Race", date: "2025-09-28", city: "Pittsburgh", state: "PA", distance: "10K", surface: "Road", elevation: "Rolling", description: "Pittsburgh's premier running event since 1977, a 10K point-to-point course finishing in Point State Park.", website: "https://www.rungreatrace.com", registrationUrl: "https://www.rungreatrace.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 40.4406, lng: -79.9959, qualityScore: 78 },
  { slug: "disney-half-marathon", name: "Walt Disney World Half Marathon", date: "2025-01-12", city: "Orlando", state: "FL", distance: "Half Marathon", surface: "Road", elevation: "Flat", description: "Run through all four Walt Disney World theme parks on this magical half marathon through the happiest place on Earth.", website: "https://www.rundisney.com", registrationUrl: "https://www.rundisney.com/events/disneyworld/disneyworld-marathon-weekend/", startTime: "5:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 28.3852, lng: -81.5639, qualityScore: 85 },
  { slug: "savannah-half-marathon", name: "Savannah Rock 'n' Roll Half Marathon", date: "2025-11-08", city: "Savannah", state: "GA", distance: "Half Marathon", surface: "Road", elevation: "Flat", description: "Run through Savannah's beautiful historic district, passing iconic squares draped in Spanish moss.", website: "https://www.runrocknroll.com/savannah", registrationUrl: "https://www.runrocknroll.com/savannah", startTime: "7:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 32.0809, lng: -81.0912, qualityScore: 80 },
  { slug: "golden-gate-half", name: "Golden Gate Half Marathon", date: "2025-11-02", city: "San Francisco", state: "CA", distance: "Half Marathon", surface: "Road", elevation: "Hilly", description: "Cross the Golden Gate Bridge on this scenic half marathon through the Presidio and along San Francisco's waterfront.", website: "https://www.goldengatehalf.com", registrationUrl: "https://www.goldengatehalf.com/register/", startTime: "7:30 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 37.7749, lng: -122.4194, qualityScore: 82 },

  // === 10K RACES ===
  { slug: "peachtree-road-race", name: "AJC Peachtree Road Race", date: "2025-07-04", city: "Atlanta", state: "GA", distance: "10K", surface: "Road", elevation: "Rolling", description: "The world's largest 10K, held every Fourth of July. A beloved Atlanta tradition since 1970.", website: "https://www.atlantatrackclub.org/peachtree-road-race", registrationUrl: "https://www.atlantatrackclub.org/peachtree-road-race", startTime: "6:25 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 33.7490, lng: -84.3880, qualityScore: 92 },
  { slug: "bolder-boulder", name: "BOLDERBoulder 10K", date: "2025-05-26", city: "Boulder", state: "CO", distance: "10K", surface: "Road", elevation: "Rolling", description: "One of the largest 10K races in the US, featuring live music, entertainment, and a finish inside Folsom Field.", website: "https://www.bolderboulder.com", registrationUrl: "https://www.bolderboulder.com/register/", startTime: "7:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 40.0150, lng: -105.2705, qualityScore: 90 },
  { slug: "cherry-blossom-10-miler", name: "Credit Union Cherry Blossom Ten Mile Run", date: "2025-04-06", city: "Washington", state: "DC", distance: "Other", surface: "Road", elevation: "Flat", description: "Run alongside the Tidal Basin's iconic cherry blossoms during peak bloom in the nation's capital.", website: "https://www.cherryblossom.org", registrationUrl: "https://www.cherryblossom.org/register/", startTime: "7:30 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10 Mile", distanceMeters: 16093, lat: 38.9072, lng: -77.0369, qualityScore: 90 },
  { slug: "bay-to-breakers", name: "Bay to Breakers", date: "2025-05-18", city: "San Francisco", state: "CA", distance: "Other", surface: "Road", elevation: "Hilly", description: "San Francisco's legendary 12K race and costume party, running from the Embarcadero to Ocean Beach since 1912.", website: "https://www.baytobreakers.com", registrationUrl: "https://www.baytobreakers.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "12K", distanceMeters: 12000, lat: 37.7749, lng: -122.4194, qualityScore: 88 },
  { slug: "cooper-river-bridge-run", name: "Cooper River Bridge Run", date: "2025-04-05", city: "Charleston", state: "SC", distance: "10K", surface: "Road", elevation: "Hilly", description: "Cross the iconic Ravenel Bridge over the Cooper River in this beloved Charleston tradition with stunning harbor views.", website: "https://www.bridgerun.com", registrationUrl: "https://www.bridgerun.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 32.7765, lng: -79.9311, qualityScore: 85 },
  { slug: "crescent-city-classic", name: "Crescent City Classic 10K", date: "2025-04-12", city: "New Orleans", state: "LA", distance: "10K", surface: "Road", elevation: "Flat", description: "One of the largest 10K races in the US, running through the French Quarter and finishing in City Park.", website: "https://www.ccc10k.com", registrationUrl: "https://www.ccc10k.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 29.9511, lng: -90.0715, qualityScore: 82 },
  { slug: "wharf-to-wharf", name: "Wharf to Wharf Race", date: "2025-07-27", city: "Santa Cruz", state: "CA", distance: "10K", surface: "Road", elevation: "Rolling", description: "A scenic 10K along the Pacific coast from Santa Cruz to Capitola, one of California's most beloved races.", website: "https://www.wharftowharf.com", registrationUrl: "https://www.wharftowharf.com/registration/", startTime: "8:30 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 36.9741, lng: -122.0308, qualityScore: 80 },
  { slug: "boilermaker-road-race", name: "Boilermaker 15K", date: "2025-07-13", city: "Utica", state: "NY", distance: "Other", surface: "Road", elevation: "Hilly", description: "One of the premier 15K road races in the US, finishing at the Saranac Brewery with free beer.", website: "https://www.boilermaker.com", registrationUrl: "https://www.boilermaker.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "15K", distanceMeters: 15000, lat: 43.1009, lng: -75.2327, qualityScore: 82 },
  { slug: "falmouth-road-race", name: "New Balance Falmouth Road Race", date: "2025-08-17", city: "Falmouth", state: "MA", distance: "Other", surface: "Road", elevation: "Rolling", description: "A scenic 7-mile road race along the Cape Cod coast, one of the most prestigious non-marathon road races in the US.", website: "https://www.falmouthroadrace.com", registrationUrl: "https://www.falmouthroadrace.com/registration/", startTime: "9:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "7 Mile", distanceMeters: 11265, lat: 41.5514, lng: -70.6148, qualityScore: 88 },

  // === 5K RACES ===
  { slug: "shamrock-run-portland", name: "Shamrock Run Portland", date: "2025-03-16", city: "Portland", state: "OR", distance: "5K", surface: "Road", elevation: "Flat", description: "Portland's biggest running party celebrating St. Patrick's Day with a 5K through the city's waterfront district.", website: "https://www.shamrockrunportland.com", registrationUrl: "https://www.shamrockrunportland.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "5K", distanceMeters: 5000, lat: 45.5152, lng: -122.6784, qualityScore: 72 },
  { slug: "turkey-trot-dallas", name: "Dallas YMCA Turkey Trot", date: "2025-11-27", city: "Dallas", state: "TX", distance: "5K", surface: "Road", elevation: "Flat", description: "One of the largest Thanksgiving Day races in the US, a Dallas tradition since 1968 through downtown.", website: "https://thetrot.org", registrationUrl: "https://thetrot.org/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "5K", distanceMeters: 5000, lat: 32.7767, lng: -96.7970, qualityScore: 78 },
  { slug: "turkey-trot-cincinnati", name: "Cincinnati Thanksgiving Day Race", date: "2025-11-27", city: "Cincinnati", state: "OH", distance: "10K", surface: "Road", elevation: "Hilly", description: "One of the oldest Thanksgiving Day races in the US, running since 1907 through downtown Cincinnati.", website: "https://www.thanksgivingdayrace.com", registrationUrl: "https://www.thanksgivingdayrace.com/register/", startTime: "9:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "10K", distanceMeters: 10000, lat: 39.1031, lng: -84.5120, qualityScore: 78 },
  { slug: "hot-chocolate-5k-philly", name: "Hot Chocolate 5K Philadelphia", date: "2025-04-06", city: "Philadelphia", state: "PA", distance: "5K", surface: "Road", elevation: "Flat", description: "A sweet-themed 5K through Philadelphia's scenic neighborhoods with chocolate fondue at the finish line.", website: "https://www.hotchocolate15k.com/philadelphia", registrationUrl: "https://www.hotchocolate15k.com/philadelphia", startTime: "7:30 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "5K", distanceMeters: 5000, lat: 39.9526, lng: -75.1652, qualityScore: 70 },
  { slug: "jingle-all-the-way-5k", name: "Jingle All The Way 5K", date: "2025-12-07", city: "Washington", state: "DC", distance: "5K", surface: "Road", elevation: "Flat", description: "A festive holiday-themed 5K through the National Mall with runners decked out in Santa suits and holiday costumes.", website: "https://www.jinglealltheway5k.com", registrationUrl: "https://www.jinglealltheway5k.com/register/", startTime: "9:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "5K", distanceMeters: 5000, lat: 38.9072, lng: -77.0369, qualityScore: 68 },
  { slug: "color-run-5k", name: "The Color Run 5K", date: "2025-09-20", city: "Los Angeles", state: "CA", distance: "5K", surface: "Road", elevation: "Flat", description: "The Happiest 5K on the Planet, where runners are doused in color at each kilometer in this fun, untimed event.", website: "https://thecolorrun.com", registrationUrl: "https://thecolorrun.com/register/", startTime: "8:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "5K", distanceMeters: 5000, lat: 34.0522, lng: -118.2437, qualityScore: 68 },

  // === TRAIL & ULTRA RACES ===
  { slug: "western-states", name: "Western States 100", date: "2025-06-28", city: "Auburn", state: "CA", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "The world's oldest 100-mile trail race, from Squaw Valley to Auburn through the Sierra Nevada mountains.", website: "https://www.wser.org", registrationUrl: "https://www.wser.org/lottery/", startTime: "5:00 AM", timeLimit: "30 hours", bostonQualifier: false, distanceLabel: "100 Mile", distanceMeters: 160934, lat: 38.8966, lng: -121.0769, qualityScore: 95 },
  { slug: "leadville-100", name: "Leadville Trail 100 Run", date: "2025-08-16", city: "Leadville", state: "CO", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "The 'Race Across the Sky' at 10,000+ feet elevation through the Colorado Rockies. One of the most legendary ultras.", website: "https://www.leadvilleraceseries.com/run/leadvilletrail100run/", registrationUrl: "https://www.leadvilleraceseries.com/run/leadvilletrail100run/", startTime: "4:00 AM", timeLimit: "30 hours", bostonQualifier: false, distanceLabel: "100 Mile", distanceMeters: 160934, lat: 39.2508, lng: -106.2925, qualityScore: 93 },
  { slug: "hardrock-100", name: "Hardrock Hundred Endurance Run", date: "2025-07-11", city: "Silverton", state: "CO", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "One of the most challenging 100-mile races in the world, with 33,000 feet of elevation gain through the San Juan Mountains.", website: "https://hardrock100.com", registrationUrl: "https://hardrock100.com/entry.php", startTime: "6:00 AM", timeLimit: "48 hours", bostonQualifier: false, distanceLabel: "100 Mile", distanceMeters: 160934, lat: 37.8119, lng: -107.6646, qualityScore: 92 },
  { slug: "jfk-50", name: "JFK 50 Mile", date: "2025-11-22", city: "Boonsboro", state: "MD", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "The oldest ultramarathon in the US, following the Appalachian Trail, C&O Canal towpath, and country roads.", website: "https://www.jfk50mile.org", registrationUrl: "https://www.jfk50mile.org/register.php", startTime: "6:00 AM", timeLimit: "13 hours", bostonQualifier: false, distanceLabel: "50 Mile", distanceMeters: 80467, lat: 39.5065, lng: -77.6536, qualityScore: 88 },
  { slug: "dipsea", name: "Dipsea Race", date: "2025-06-08", city: "Mill Valley", state: "CA", distance: "Other", surface: "Trail", elevation: "Mountainous", description: "The oldest trail race in America. A 7.4-mile single-track adventure from Mill Valley to Stinson Beach through Muir Woods.", website: "https://www.dipsea.org", registrationUrl: "https://www.dipsea.org/race/entry.html", startTime: "8:30 AM", timeLimit: "3 hours", bostonQualifier: false, distanceLabel: "7.4 Mile", distanceMeters: 11909, lat: 37.9060, lng: -122.5450, qualityScore: 88 },
  { slug: "wasatch-front-100", name: "Wasatch Front 100", date: "2025-09-05", city: "Kaysville", state: "UT", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "A brutal 100-mile trail run through the Wasatch Mountains with over 26,000 feet of climbing.", website: "https://www.wasatch100.com", registrationUrl: "https://www.wasatch100.com/registration/", startTime: "5:00 AM", timeLimit: "36 hours", bostonQualifier: false, distanceLabel: "100 Mile", distanceMeters: 160934, lat: 41.0352, lng: -111.9385, qualityScore: 85 },
  { slug: "pikes-peak-marathon", name: "Pikes Peak Marathon", date: "2025-08-17", city: "Manitou Springs", state: "CO", distance: "Marathon", surface: "Trail", elevation: "Mountainous", description: "America's ultimate challenge: summit 14,115-foot Pikes Peak and descend back to Manitou Springs in this grueling trail marathon.", website: "https://pikespeakmarathon.org", registrationUrl: "https://pikespeakmarathon.org/registration/", startTime: "7:00 AM", timeLimit: "10 hours", bostonQualifier: false, distanceLabel: "Marathon", distanceMeters: 42195, lat: 38.8586, lng: -104.9172, qualityScore: 88 },
  { slug: "mount-washington-road-race", name: "Mount Washington Road Race", date: "2025-06-21", city: "Gorham", state: "NH", distance: "Other", surface: "Road", elevation: "Mountainous", description: "A 7.6-mile race straight up the Mt. Washington Auto Road, gaining 4,650 feet to the summit of the Northeast's highest peak.", website: "https://www.mountwashingtonroadrace.com", registrationUrl: "https://www.mountwashingtonroadrace.com/register/", startTime: "9:00 AM", timeLimit: "3 hours", bostonQualifier: false, distanceLabel: "7.6 Mile", distanceMeters: 12231, lat: 44.3386, lng: -71.1854, qualityScore: 86 },
  { slug: "imogene-pass-run", name: "Imogene Pass Run", date: "2025-09-06", city: "Ouray", state: "CO", distance: "Other", surface: "Trail", elevation: "Mountainous", description: "A legendary 17.1-mile trail race over 13,114-foot Imogene Pass from Ouray to Telluride in the San Juan Mountains.", website: "https://www.imogenerun.com", registrationUrl: "https://www.imogenerun.com/registration/", startTime: "8:00 AM", timeLimit: "7 hours", bostonQualifier: false, distanceLabel: "17.1 Mile", distanceMeters: 27519, lat: 38.0228, lng: -107.6714, qualityScore: 85 },
  { slug: "javelina-jundred", name: "Javelina Jundred 100 Mile", date: "2025-10-25", city: "Fountain Hills", state: "AZ", distance: "Ultra", surface: "Trail", elevation: "Rolling", description: "A fast 100-mile desert trail race through McDowell Mountain Regional Park, known for its festive Halloween-weekend atmosphere.", website: "https://www.aravaipauunning.com/javelina-jundred/", registrationUrl: "https://www.aravaiparunning.com/javelina-jundred/", startTime: "6:00 AM", timeLimit: "30 hours", bostonQualifier: false, distanceLabel: "100 Mile", distanceMeters: 160934, lat: 33.6117, lng: -111.7174, qualityScore: 83 },
  { slug: "superior-100", name: "Superior 100 Mile Trail Race", date: "2025-09-12", city: "Lutsen", state: "MN", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "A grueling 100-mile trail race along the Superior Hiking Trail on Minnesota's beautiful North Shore of Lake Superior.", website: "https://www.superiorfalltrailrace.com", registrationUrl: "https://www.superiorfalltrailrace.com/100-mile-registration/", startTime: "7:00 AM", timeLimit: "38 hours", bostonQualifier: false, distanceLabel: "100 Mile", distanceMeters: 160934, lat: 47.6530, lng: -90.6982, qualityScore: 82 },
  { slug: "run-the-rut-50k", name: "Run the Rut 50K", date: "2025-09-06", city: "Big Sky", state: "MT", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "A stunning 50K skyrunning race at Big Sky Resort with extreme alpine terrain and breathtaking Montana views.", website: "https://runtherut.com", registrationUrl: "https://runtherut.com/registration/", startTime: "6:00 AM", timeLimit: "14 hours", bostonQualifier: false, distanceLabel: "50K", distanceMeters: 50000, lat: 45.2838, lng: -111.4013, qualityScore: 83 },
  { slug: "mountain-masochist-50", name: "Mountain Masochist 50 Miler", date: "2025-11-01", city: "Lynchburg", state: "VA", distance: "Ultra", surface: "Trail", elevation: "Mountainous", description: "A classic East Coast 50-mile trail race through the Blue Ridge Mountains of Virginia with challenging climbs.", website: "https://www.mountainmasochist.com", registrationUrl: "https://www.mountainmasochist.com/registration/", startTime: "6:30 AM", timeLimit: "14 hours", bostonQualifier: false, distanceLabel: "50 Mile", distanceMeters: 80467, lat: 37.4138, lng: -79.1422, qualityScore: 78 },

  // === REGIONAL FAVORITES ===
  { slug: "des-moines-marathon", name: "IMT Des Moines Marathon", date: "2025-10-19", city: "Des Moines", state: "IA", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "Iowa's premier marathon through the state capital, passing the gold-domed Capitol building and scenic Gray's Lake.", website: "https://www.desmoinesmarathon.com", registrationUrl: "https://www.desmoinesmarathon.com/register/", startTime: "7:00 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 41.5868, lng: -93.6250, qualityScore: 76 },
  { slug: "disney-marathon", name: "Walt Disney World Marathon", date: "2025-01-12", city: "Orlando", state: "FL", distance: "Marathon", surface: "Road", elevation: "Flat", description: "The most magical marathon on Earth, running through all four Walt Disney World theme parks with character photo ops.", website: "https://www.rundisney.com", registrationUrl: "https://www.rundisney.com/events/disneyworld/disneyworld-marathon-weekend/", startTime: "5:00 AM", timeLimit: "7 hours", bostonQualifier: false, distanceLabel: "Marathon", distanceMeters: 42195, lat: 28.3852, lng: -81.5639, qualityScore: 85 },
  { slug: "flying-pig-marathon", name: "Flying Pig Marathon", date: "2025-05-04", city: "Cincinnati", state: "OH", distance: "Marathon", surface: "Road", elevation: "Hilly", description: "Cincinnati's premier marathon with challenging hills and enthusiastic neighborhood support throughout the Queen City.", website: "https://www.flyingpigmarathon.com", registrationUrl: "https://www.flyingpigmarathon.com/races/marathon/", startTime: "6:30 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 39.1031, lng: -84.5120, qualityScore: 82 },
  { slug: "eugene-marathon", name: "Eugene Marathon", date: "2025-04-27", city: "Eugene", state: "OR", distance: "Marathon", surface: "Road", elevation: "Flat", description: "Run in TrackTown USA, the nation's running capital, on a fast, flat course along the Willamette River.", website: "https://www.eugenemarathon.com", registrationUrl: "https://www.eugenemarathon.com/register/", startTime: "7:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 44.0521, lng: -123.0868, qualityScore: 82 },
  { slug: "salt-lake-city-marathon", name: "Salt Lake City Marathon", date: "2025-04-19", city: "Salt Lake City", state: "UT", distance: "Marathon", surface: "Road", elevation: "Downhill", description: "A net-downhill course starting near the mouth of Big Cottonwood Canyon and finishing at the Utah State Capitol.", website: "https://www.saltlakecitymarathon.com", registrationUrl: "https://www.saltlakecitymarathon.com/register/", startTime: "7:00 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 40.7608, lng: -111.8910, qualityScore: 78 },
  { slug: "fargo-marathon", name: "Fargo Marathon", date: "2025-05-17", city: "Fargo", state: "ND", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A flat, fast BQ-friendly course through Fargo-Moorhead known for its amazing community support.", website: "https://www.fargomarathon.com", registrationUrl: "https://www.fargomarathon.com/register/", startTime: "7:00 AM", timeLimit: "6.5 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 46.8772, lng: -96.7898, qualityScore: 76 },
  { slug: "little-rock-marathon", name: "Little Rock Marathon", date: "2025-03-02", city: "Little Rock", state: "AR", distance: "Marathon", surface: "Road", elevation: "Hilly", description: "Famous for its massive finisher medals, this marathon winds through the state capital's riverfront and neighborhoods.", website: "https://www.littlerockmarathon.com", registrationUrl: "https://www.littlerockmarathon.com/register/", startTime: "7:00 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 34.7465, lng: -92.2896, qualityScore: 75 },
  { slug: "raleigh-half-marathon", name: "City of Oaks Half Marathon", date: "2025-11-02", city: "Raleigh", state: "NC", distance: "Half Marathon", surface: "Road", elevation: "Rolling", description: "A fall half marathon through Raleigh's beautiful oak-lined streets and scenic greenways.", website: "https://www.cityofoaksmarathon.com", registrationUrl: "https://www.cityofoaksmarathon.com/register/", startTime: "7:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 35.7796, lng: -78.6382, qualityScore: 75 },
  { slug: "chattanooga-marathon", name: "Chattanooga Marathon", date: "2025-03-02", city: "Chattanooga", state: "TN", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "A scenic course along the Tennessee River with views of Lookout Mountain, known as a great BQ course.", website: "https://www.chattanoogamarathon.com", registrationUrl: "https://www.chattanoogamarathon.com/register/", startTime: "7:30 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 35.0456, lng: -85.3097, qualityScore: 80 },
  { slug: "milwaukee-lakefront-marathon", name: "Milwaukee Lakefront Marathon", date: "2025-10-05", city: "Milwaukee", state: "WI", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A fast, scenic point-to-point course along Lake Michigan from Grafton to downtown Milwaukee.", website: "https://www.milwaukeelakefrontmarathon.org", registrationUrl: "https://www.milwaukeelakefrontmarathon.org/registration/", startTime: "7:30 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 43.0389, lng: -87.9065, qualityScore: 80 },
  { slug: "san-antonio-marathon", name: "Humana Rock 'n' Roll San Antonio Marathon", date: "2025-12-07", city: "San Antonio", state: "TX", distance: "Marathon", surface: "Road", elevation: "Flat", description: "Run through the heart of San Antonio past the Alamo, River Walk, and historic missions.", website: "https://www.runrocknroll.com/san-antonio", registrationUrl: "https://www.runrocknroll.com/san-antonio", startTime: "7:30 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 29.4241, lng: -98.4936, qualityScore: 80 },
  { slug: "space-coast-marathon", name: "Space Coast Marathon", date: "2025-11-30", city: "Cocoa Beach", state: "FL", distance: "Marathon", surface: "Road", elevation: "Flat", description: "A flat, fast BQ course along the Space Coast with views of the Kennedy Space Center and Atlantic Ocean.", website: "https://www.spacecoastmarathon.com", registrationUrl: "https://www.spacecoastmarathon.com/register/", startTime: "6:00 AM", timeLimit: "6 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 28.3200, lng: -80.6076, qualityScore: 76 },
  { slug: "manchester-road-race", name: "Manchester Road Race", date: "2025-11-27", city: "Manchester", state: "CT", distance: "Other", surface: "Road", elevation: "Rolling", description: "A beloved Thanksgiving Day tradition since 1927, this 4.748-mile race draws thousands to Manchester, Connecticut.", website: "https://www.manchesterroadrace.com", registrationUrl: "https://www.manchesterroadrace.com/register/", startTime: "10:00 AM", timeLimit: "None", bostonQualifier: false, distanceLabel: "4.748 Mile", distanceMeters: 7640, lat: 41.7759, lng: -72.5215, qualityScore: 82 },
  { slug: "albuquerque-half-marathon", name: "Duke City Half Marathon", date: "2025-10-19", city: "Albuquerque", state: "NM", distance: "Half Marathon", surface: "Road", elevation: "Rolling", description: "Run through Albuquerque's scenic Bosque trail and along the Rio Grande in the Land of Enchantment.", website: "https://www.dukecitymarathon.com", registrationUrl: "https://www.dukecitymarathon.com/register/", startTime: "7:00 AM", timeLimit: "4 hours", bostonQualifier: false, distanceLabel: "Half Marathon", distanceMeters: 21097, lat: 35.0844, lng: -106.6504, qualityScore: 74 },
  { slug: "anchorage-marathon", name: "Anchorage RunFest Marathon", date: "2025-08-16", city: "Anchorage", state: "AK", distance: "Marathon", surface: "Road", elevation: "Rolling", description: "Run through Alaska's largest city with views of the Chugach Mountains and Cook Inlet on this scenic summer course.", website: "https://www.anchoragerunfest.org", registrationUrl: "https://www.anchoragerunfest.org/register/", startTime: "8:00 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 61.2181, lng: -149.9003, qualityScore: 74 },
  { slug: "boise-half-marathon", name: "Famous Idaho Potato Marathon", date: "2025-05-17", city: "Boise", state: "ID", distance: "Marathon", surface: "Road", elevation: "Downhill", description: "A net-downhill course from the mountains above Boise to the finish at the Idaho State Capitol.", website: "https://www.famousidahopotatomarathon.com", registrationUrl: "https://www.famousidahopotatomarathon.com/register/", startTime: "7:00 AM", timeLimit: "7 hours", bostonQualifier: true, distanceLabel: "Marathon", distanceMeters: 42195, lat: 43.6150, lng: -116.2023, qualityScore: 74 },
];

const SEED_ROUTES: InsertRoute[] = [
  // === NEW YORK CITY ===
  { slug: "central-park-loop", name: "Central Park Full Loop", city: "New York City", state: "NY", distance: 6.1, elevationGain: 280, surface: "Road", type: "Loop", difficulty: "Moderate", description: "The classic NYC running loop through Central Park. Paved paths with rolling hills, water fountains, and restrooms.", distanceMeters: 9817, lat: 40.7829, lng: -73.9654, qualityScore: 92 },
  { slug: "central-park-reservoir", name: "Central Park Reservoir Loop", city: "New York City", state: "NY", distance: 1.6, elevationGain: 20, surface: "Path", type: "Loop", difficulty: "Easy", description: "The iconic Jacqueline Kennedy Onassis Reservoir loop with stunning Manhattan skyline views on a soft cinder path.", distanceMeters: 2575, lat: 40.7856, lng: -73.9632, qualityScore: 88 },
  { slug: "hudson-river-greenway", name: "Hudson River Greenway", city: "New York City", state: "NY", distance: 11.0, elevationGain: 40, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "A flat, paved waterfront path along the Hudson River from Battery Park to the George Washington Bridge.", distanceMeters: 17703, lat: 40.7413, lng: -74.0089, qualityScore: 90 },
  { slug: "prospect-park-loop", name: "Prospect Park Loop", city: "New York City", state: "NY", distance: 3.35, elevationGain: 150, surface: "Road", type: "Loop", difficulty: "Moderate", description: "Brooklyn's premier running loop through Frederick Law Olmsted's scenic park with rolling hills and tree-lined paths.", distanceMeters: 5392, lat: 40.6602, lng: -73.9690, qualityScore: 86 },
  { slug: "east-river-greenway", name: "East River Greenway", city: "New York City", state: "NY", distance: 8.5, elevationGain: 30, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "A flat waterfront path along Manhattan's East River with views of the Brooklyn Bridge and Williamsburg Bridge.", distanceMeters: 13679, lat: 40.7089, lng: -74.0012, qualityScore: 84 },

  // === BOSTON ===
  { slug: "charles-river-esplanade", name: "Charles River Esplanade", city: "Boston", state: "MA", distance: 3.0, elevationGain: 20, surface: "Path", type: "Loop", difficulty: "Easy", description: "A flat, scenic loop along the Charles River with views of the Boston skyline and MIT campus.", distanceMeters: 4828, lat: 42.3551, lng: -71.0773, qualityScore: 88 },
  { slug: "charles-river-full-loop", name: "Charles River Full Loop", city: "Boston", state: "MA", distance: 17.0, elevationGain: 100, surface: "Path", type: "Loop", difficulty: "Moderate", description: "The full loop around the Charles River from the Museum of Science to Watertown and back, crossing multiple bridges.", distanceMeters: 27359, lat: 42.3601, lng: -71.0689, qualityScore: 86 },
  { slug: "emerald-necklace", name: "Emerald Necklace Loop", city: "Boston", state: "MA", distance: 7.0, elevationGain: 180, surface: "Path", type: "Loop", difficulty: "Moderate", description: "Frederick Law Olmsted's chain of parks from Boston Common to Franklin Park through the Back Bay Fens and Jamaica Pond.", distanceMeters: 11265, lat: 42.3401, lng: -71.1032, qualityScore: 85 },
  { slug: "minuteman-bikeway", name: "Minuteman Bikeway Trail", city: "Cambridge", state: "MA", distance: 10.0, elevationGain: 60, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "A paved rail-trail from Cambridge to Bedford, following the route Paul Revere rode in 1775.", distanceMeters: 16093, lat: 42.3956, lng: -71.1427, qualityScore: 82 },

  // === CHICAGO ===
  { slug: "lakefront-trail", name: "Chicago Lakefront Trail", city: "Chicago", state: "IL", distance: 18.0, elevationGain: 50, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "An 18-mile paved trail along Lake Michigan, one of the most popular running paths in the Midwest.", distanceMeters: 28968, lat: 41.8924, lng: -87.6088, qualityScore: 92 },
  { slug: "606-trail-chicago", name: "The 606 (Bloomingdale Trail)", city: "Chicago", state: "IL", distance: 2.7, elevationGain: 10, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "An elevated rail-trail park running through four Chicago neighborhoods, offering unique urban views from above street level.", distanceMeters: 4345, lat: 41.9148, lng: -87.6873, qualityScore: 80 },

  // === SAN FRANCISCO BAY AREA ===
  { slug: "crissy-field", name: "Crissy Field to Golden Gate Bridge", city: "San Francisco", state: "CA", distance: 4.5, elevationGain: 120, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A flat waterfront path with stunning views of the Golden Gate Bridge. Popular with joggers and walkers alike.", distanceMeters: 7242, lat: 37.8040, lng: -122.4646, qualityScore: 88 },
  { slug: "lands-end-trail", name: "Lands End Trail", city: "San Francisco", state: "CA", distance: 3.4, elevationGain: 400, surface: "Trail", type: "Out-and-Back", difficulty: "Moderate", description: "A scenic coastal trail with views of the Golden Gate Bridge, Marin Headlands, and the Pacific Ocean.", distanceMeters: 5472, lat: 37.7878, lng: -122.5111, qualityScore: 86 },
  { slug: "presidio-trails", name: "Presidio Loop Trail", city: "San Francisco", state: "CA", distance: 4.0, elevationGain: 350, surface: "Trail", type: "Loop", difficulty: "Moderate", description: "A loop through the Presidio's forested trails and historic batteries with views of the Bay and Golden Gate Bridge.", distanceMeters: 6437, lat: 37.7989, lng: -122.4662, qualityScore: 84 },
  { slug: "sawyer-camp-trail", name: "Sawyer Camp Trail", city: "San Mateo", state: "CA", distance: 6.0, elevationGain: 200, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A scenic paved trail through Crystal Springs Reservoir surrounded by rolling hills and oak groves on the Peninsula.", distanceMeters: 9656, lat: 37.5268, lng: -122.3580, qualityScore: 80 },

  // === LOS ANGELES ===
  { slug: "runyon-canyon", name: "Runyon Canyon Loop", city: "Los Angeles", state: "CA", distance: 3.5, elevationGain: 800, surface: "Trail", type: "Loop", difficulty: "Hard", description: "A popular LA trail with steep climbs and panoramic views of the Hollywood Sign and downtown skyline.", distanceMeters: 5633, lat: 34.1060, lng: -118.3484, qualityScore: 86 },
  { slug: "griffith-park-trail", name: "Griffith Park Trail to Observatory", city: "Los Angeles", state: "CA", distance: 5.0, elevationGain: 900, surface: "Trail", type: "Out-and-Back", difficulty: "Hard", description: "A challenging trail run to the Griffith Observatory with sweeping views of the LA basin and Hollywood Sign.", distanceMeters: 8047, lat: 34.1184, lng: -118.3004, qualityScore: 85 },
  { slug: "santa-monica-beach-path", name: "Santa Monica Beach Path", city: "Santa Monica", state: "CA", distance: 8.5, elevationGain: 20, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A flat beachfront path along the Pacific from Santa Monica Pier to Marina del Rey with ocean breezes.", distanceMeters: 13679, lat: 34.0195, lng: -118.4912, qualityScore: 84 },
  { slug: "temescal-gateway-loop", name: "Temescal Gateway Loop", city: "Los Angeles", state: "CA", distance: 4.2, elevationGain: 850, surface: "Trail", type: "Loop", difficulty: "Hard", description: "A steep loop in Pacific Palisades with ocean views and wildflower meadows in the Santa Monica Mountains.", distanceMeters: 6759, lat: 34.0468, lng: -118.5293, qualityScore: 80 },

  // === AUSTIN ===
  { slug: "lady-bird-lake", name: "Lady Bird Lake Loop", city: "Austin", state: "TX", distance: 10.1, elevationGain: 100, surface: "Path", type: "Loop", difficulty: "Easy", description: "A scenic loop around Lady Bird Lake in downtown Austin. Crushed granite trail with shade and water views.", distanceMeters: 16255, lat: 30.2500, lng: -97.7500, qualityScore: 90 },
  { slug: "town-lake-boardwalk", name: "Town Lake Boardwalk", city: "Austin", state: "TX", distance: 1.3, elevationGain: 10, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A flat, accessible boardwalk section along Lady Bird Lake. Perfect for easy recovery runs.", distanceMeters: 2092, lat: 30.2574, lng: -97.7402, qualityScore: 75 },
  { slug: "barton-creek-greenbelt", name: "Barton Creek Greenbelt", city: "Austin", state: "TX", distance: 7.9, elevationGain: 450, surface: "Trail", type: "Out-and-Back", difficulty: "Moderate", description: "A popular trail through limestone cliffs and creek crossings in the heart of Austin, with swimming holes.", distanceMeters: 12714, lat: 30.2451, lng: -97.7950, qualityScore: 85 },

  // === DENVER / BOULDER ===
  { slug: "boulder-creek-path", name: "Boulder Creek Path", city: "Boulder", state: "CO", distance: 5.5, elevationGain: 200, surface: "Path", type: "Out-and-Back", difficulty: "Moderate", description: "A popular multi-use path following Boulder Creek from Eben G. Fine Park to the eastern plains.", distanceMeters: 8851, lat: 40.0150, lng: -105.2828, qualityScore: 85 },
  { slug: "cherry-creek-trail-denver", name: "Cherry Creek Trail", city: "Denver", state: "CO", distance: 12.0, elevationGain: 100, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "A paved trail following Cherry Creek from Confluence Park to Cherry Creek Reservoir through the heart of Denver.", distanceMeters: 19312, lat: 39.7520, lng: -104.9998, qualityScore: 84 },
  { slug: "mount-sanitas-loop", name: "Mount Sanitas Loop", city: "Boulder", state: "CO", distance: 3.3, elevationGain: 1300, surface: "Trail", type: "Loop", difficulty: "Hard", description: "A steep, rocky trail to the summit of Mt. Sanitas with panoramic views of Boulder and the Flatirons.", distanceMeters: 5311, lat: 40.0215, lng: -105.2991, qualityScore: 83 },

  // === PORTLAND ===
  { slug: "forest-park-wildwood", name: "Wildwood Trail (End-to-End)", city: "Portland", state: "OR", distance: 30.2, elevationGain: 2500, surface: "Trail", type: "Point-to-Point", difficulty: "Hard", description: "The longest continuous trail in Portland's Forest Park. A challenging end-to-end run through old-growth forest.", distanceMeters: 48603, lat: 45.5370, lng: -122.7160, qualityScore: 88 },
  { slug: "springwater-corridor", name: "Springwater Corridor Trail", city: "Portland", state: "OR", distance: 21.0, elevationGain: 150, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "A flat, paved rail-trail from SE Portland to Boring, following Johnson Creek through parks and wetlands.", distanceMeters: 33796, lat: 45.4778, lng: -122.5829, qualityScore: 80 },

  // === SEATTLE ===
  { slug: "burke-gilman-trail", name: "Burke-Gilman Trail", city: "Seattle", state: "WA", distance: 27.0, elevationGain: 300, surface: "Path", type: "Point-to-Point", difficulty: "Moderate", description: "A paved multi-use trail running from the Ballard Locks to the Sammamish River Trail near Bothell.", distanceMeters: 43452, lat: 47.6584, lng: -122.3883, qualityScore: 88 },
  { slug: "green-lake-loop", name: "Green Lake Loop", city: "Seattle", state: "WA", distance: 2.8, elevationGain: 15, surface: "Path", type: "Loop", difficulty: "Easy", description: "A flat, scenic loop around Green Lake, one of Seattle's most popular year-round running paths.", distanceMeters: 4506, lat: 47.6800, lng: -122.3400, qualityScore: 85 },
  { slug: "discovery-park-loop", name: "Discovery Park Loop Trail", city: "Seattle", state: "WA", distance: 2.8, elevationGain: 200, surface: "Trail", type: "Loop", difficulty: "Moderate", description: "A scenic loop through Seattle's largest park with bluffs overlooking Puget Sound and the Olympic Mountains.", distanceMeters: 4506, lat: 47.6573, lng: -122.4175, qualityScore: 82 },

  // === WASHINGTON DC ===
  { slug: "national-mall-loop", name: "National Mall Loop", city: "Washington", state: "DC", distance: 4.3, elevationGain: 40, surface: "Path", type: "Loop", difficulty: "Easy", description: "A flat loop around the National Mall passing the Lincoln Memorial, Washington Monument, and the US Capitol.", distanceMeters: 6920, lat: 38.8895, lng: -77.0353, qualityScore: 90 },
  { slug: "rock-creek-trail-dc", name: "Rock Creek Park Trail", city: "Washington", state: "DC", distance: 9.0, elevationGain: 300, surface: "Trail", type: "Point-to-Point", difficulty: "Moderate", description: "A forested trail through the heart of DC's largest park, following Rock Creek from the National Zoo to the Maryland border.", distanceMeters: 14484, lat: 38.9579, lng: -77.0494, qualityScore: 84 },
  { slug: "mt-vernon-trail", name: "Mount Vernon Trail", city: "Arlington", state: "VA", distance: 18.0, elevationGain: 200, surface: "Path", type: "Point-to-Point", difficulty: "Moderate", description: "A scenic paved trail along the Potomac River from Roosevelt Island to George Washington's Mount Vernon estate.", distanceMeters: 28968, lat: 38.8799, lng: -77.0688, qualityScore: 86 },

  // === PHILADELPHIA ===
  { slug: "schuylkill-river-trail", name: "Schuylkill River Trail", city: "Philadelphia", state: "PA", distance: 8.5, elevationGain: 80, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A scenic paved trail along the Schuylkill River passing Boathouse Row and the Philadelphia Museum of Art.", distanceMeters: 13679, lat: 39.9670, lng: -75.1870, qualityScore: 88 },
  { slug: "wissahickon-trail", name: "Forbidden Drive (Wissahickon Valley)", city: "Philadelphia", state: "PA", distance: 5.5, elevationGain: 100, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A flat, car-free gravel path through the scenic Wissahickon Valley alongside Wissahickon Creek.", distanceMeters: 8851, lat: 40.0525, lng: -75.2099, qualityScore: 85 },

  // === MIAMI ===
  { slug: "south-beach-boardwalk", name: "South Beach Boardwalk", city: "Miami", state: "FL", distance: 4.0, elevationGain: 5, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A flat boardwalk and path along iconic South Beach with ocean breezes and Art Deco architecture views.", distanceMeters: 6437, lat: 25.7825, lng: -80.1340, qualityScore: 82 },
  { slug: "key-biscayne-loop", name: "Key Biscayne Loop", city: "Miami", state: "FL", distance: 8.0, elevationGain: 15, surface: "Path", type: "Loop", difficulty: "Easy", description: "A scenic loop around Key Biscayne with views of Biscayne Bay, the Miami skyline, and Atlantic Ocean.", distanceMeters: 12875, lat: 25.6940, lng: -80.1625, qualityScore: 80 },

  // === SAN DIEGO ===
  { slug: "mission-bay-loop", name: "Mission Bay Loop", city: "San Diego", state: "CA", distance: 12.0, elevationGain: 30, surface: "Path", type: "Loop", difficulty: "Easy", description: "A flat waterfront loop around Mission Bay with stunning Pacific views and consistent sea breezes.", distanceMeters: 19312, lat: 32.7761, lng: -117.2355, qualityScore: 86 },
  { slug: "torrey-pines-trail", name: "Torrey Pines State Reserve Trail", city: "San Diego", state: "CA", distance: 3.5, elevationGain: 400, surface: "Trail", type: "Loop", difficulty: "Moderate", description: "Coastal bluff trails through rare Torrey pine groves with sweeping Pacific Ocean views in this stunning reserve.", distanceMeters: 5633, lat: 32.9200, lng: -117.2542, qualityScore: 84 },

  // === NATIONAL PARK ROUTES ===
  { slug: "zion-angels-landing", name: "Angels Landing Trail", city: "Springdale", state: "UT", distance: 5.4, elevationGain: 1488, surface: "Trail", type: "Out-and-Back", difficulty: "Hard", description: "A thrilling trail in Zion National Park ascending to a narrow ridge with 1,000-foot drop-offs and stunning canyon views.", distanceMeters: 8690, lat: 37.2692, lng: -112.9471, qualityScore: 90 },
  { slug: "grand-canyon-south-kaibab", name: "South Kaibab Trail", city: "Grand Canyon Village", state: "AZ", distance: 6.0, elevationGain: 2040, surface: "Trail", type: "Out-and-Back", difficulty: "Hard", description: "A steep, exposed trail descending into the Grand Canyon from the South Rim with panoramic canyon views.", distanceMeters: 9656, lat: 36.0544, lng: -112.0838, qualityScore: 88 },
  { slug: "mount-rainier-wonderland", name: "Wonderland Trail (Section)", city: "Ashford", state: "WA", distance: 10.0, elevationGain: 2500, surface: "Trail", type: "Out-and-Back", difficulty: "Hard", description: "A section of the 93-mile Wonderland Trail circling Mount Rainier through alpine meadows and old-growth forest.", distanceMeters: 16093, lat: 46.7869, lng: -121.7356, qualityScore: 88 },
  { slug: "acadia-carriage-roads", name: "Acadia Carriage Roads Loop", city: "Bar Harbor", state: "ME", distance: 6.0, elevationGain: 300, surface: "Path", type: "Loop", difficulty: "Moderate", description: "Historic broken-stone carriage roads in Acadia National Park with views of Jordan Pond and the granite peaks.", distanceMeters: 9656, lat: 44.3386, lng: -68.2733, qualityScore: 86 },

  // === ADDITIONAL CITIES ===
  { slug: "minneapolis-chain-of-lakes", name: "Chain of Lakes Loop", city: "Minneapolis", state: "MN", distance: 13.0, elevationGain: 80, surface: "Path", type: "Loop", difficulty: "Moderate", description: "A scenic loop connecting Lake Harriet, Lake Calhoun (Bde Maka Ska), Lake of the Isles, and Cedar Lake.", distanceMeters: 20921, lat: 44.9480, lng: -93.3088, qualityScore: 86 },
  { slug: "katy-trail-dallas", name: "Katy Trail", city: "Dallas", state: "TX", distance: 3.5, elevationGain: 20, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A popular paved trail through Uptown Dallas built on a former railroad corridor, lined with trees and parks.", distanceMeters: 5633, lat: 32.8058, lng: -96.8069, qualityScore: 80 },
  { slug: "buffalo-bayou-trail", name: "Buffalo Bayou Trail", city: "Houston", state: "TX", distance: 7.5, elevationGain: 40, surface: "Path", type: "Out-and-Back", difficulty: "Easy", description: "A paved trail along Buffalo Bayou from downtown Houston through Memorial Park with skyline views.", distanceMeters: 12070, lat: 29.7634, lng: -95.3905, qualityScore: 82 },
  { slug: "monon-trail-indy", name: "Monon Trail", city: "Indianapolis", state: "IN", distance: 18.0, elevationGain: 100, surface: "Path", type: "Point-to-Point", difficulty: "Easy", description: "A popular rail-trail from downtown Indianapolis through Broad Ripple to Carmel, passing shops and restaurants.", distanceMeters: 28968, lat: 39.8362, lng: -86.1428, qualityScore: 80 },
  { slug: "piedmont-park-loop", name: "Piedmont Park Loop", city: "Atlanta", state: "GA", distance: 3.1, elevationGain: 100, surface: "Path", type: "Loop", difficulty: "Easy", description: "A scenic loop through Atlanta's premier urban park with views of the Midtown skyline and rolling green lawns.", distanceMeters: 4989, lat: 33.7879, lng: -84.3742, qualityScore: 82 },
  { slug: "town-lake-trail-tempe", name: "Tempe Town Lake Loop", city: "Tempe", state: "AZ", distance: 5.0, elevationGain: 15, surface: "Path", type: "Loop", difficulty: "Easy", description: "A flat loop around Tempe Town Lake with views of the desert mountains and Arizona State University campus.", distanceMeters: 8047, lat: 33.4316, lng: -111.9283, qualityScore: 78 },
  { slug: "river-walk-san-antonio", name: "San Antonio River Walk Trail", city: "San Antonio", state: "TX", distance: 4.0, elevationGain: 20, surface: "Path", type: "Loop", difficulty: "Easy", description: "A scenic path along the famous San Antonio River Walk, extending beyond the tourist district into quieter parkland.", distanceMeters: 6437, lat: 29.4241, lng: -98.4936, qualityScore: 78 },
];

const SEED_SOURCES: InsertSource[] = [
  { name: "manual", type: "manual", priority: 0 },
  { name: "runsignup", type: "api", baseUrl: "https://runsignup.com", priority: 10 },
  { name: "active", type: "api", baseUrl: "https://www.active.com", priority: 5 },
];

const SEED_COLLECTIONS: InsertCollection[] = [
  { type: "races", slug: "best-marathons-usa", title: "Best Marathons in the USA", description: "The top-rated marathon races across all 50 states, from world majors to hidden gems.", queryJson: { distance: "Marathon", limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "races", slug: "boston-qualifying-marathons", title: "Boston Qualifying Marathons", description: "Marathons known for fast courses and high BQ rates. Find your next qualifying race.", queryJson: { distance: "Marathon", bostonQualifier: true }, isProgrammatic: false, isActive: true },
  { type: "races", slug: "best-half-marathons", title: "Best Half Marathons in the USA", description: "Top-rated half marathon events perfect for your next 13.1-mile challenge.", queryJson: { distance: "Half Marathon", limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "races", slug: "best-trail-races", title: "Best Trail Races in the USA", description: "Premier trail running events from technical mountain ultras to scenic forest races.", queryJson: { surface: "Trail", limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "races", slug: "best-10k-races", title: "Best 10K Races in the USA", description: "The top 10K races across America, from the world's largest to scenic coastal courses.", queryJson: { distance: "10K", limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "races", slug: "best-fall-races", title: "Best Fall Races", description: "The best races to run in September, October, and November when the weather cools and fall foliage peaks.", queryJson: { monthRange: [9, 11], limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "races", slug: "best-spring-races", title: "Best Spring Races", description: "Top spring races from March through May, featuring cherry blossoms, perfect weather, and fast courses.", queryJson: { monthRange: [3, 5], limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "routes", slug: "best-urban-running-routes", title: "Best Urban Running Routes", description: "The most popular and scenic running routes in major US cities.", queryJson: { surface: "Path", limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "routes", slug: "best-trail-running-routes", title: "Best Trail Running Routes", description: "Top-rated trail running routes for every difficulty level.", queryJson: { surface: "Trail", limit: 20 }, isProgrammatic: false, isActive: true },
  { type: "routes", slug: "best-beginner-running-routes", title: "Best Beginner Running Routes", description: "Flat, scenic, and easy routes perfect for new runners just getting started.", queryJson: { difficulty: "Easy", limit: 20 }, isProgrammatic: false, isActive: true },
];

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

async function seedCitiesFromData() {
  const allStates = await storage.getStates();
  const stateMap = new Map(allStates.map(s => [s.abbreviation, s]));

  const citySet = new Set<string>();
  const cityInserts: InsertCity[] = [];

  const allRaces = await storage.getRaces({ limit: 10000 });
  const allRoutes = await storage.getRoutes({ limit: 10000 });

  for (const race of allRaces) {
    const key = `${race.city}|${race.state}`;
    if (!citySet.has(key)) {
      citySet.add(key);
      const stateData = stateMap.get(race.state);
      if (stateData) {
        cityInserts.push({
          name: race.city,
          slug: slugify(race.city),
          stateId: stateData.id,
        });
      }
    }
  }

  for (const route of allRoutes) {
    const key = `${route.city}|${route.state}`;
    if (!citySet.has(key)) {
      citySet.add(key);
      const stateData = stateMap.get(route.state);
      if (stateData) {
        cityInserts.push({
          name: route.city,
          slug: slugify(route.city),
          stateId: stateData.id,
        });
      }
    }
  }

  await storage.seedCities(cityInserts);
  console.log(`Seeded ${cityInserts.length} cities`);
}

async function linkRacesToCities() {
  const allCities = await storage.getCities({ limit: 10000 });
  const allStates = await storage.getStates();
  const stateMap = new Map(allStates.map(s => [s.abbreviation, s.id]));

  for (const city of allCities) {
    const stateEntry = allStates.find(s => s.id === city.stateId);
    if (!stateEntry) continue;

    await db.update(races)
      .set({ cityId: city.id, stateId: city.stateId })
      .where(eq(races.city, city.name));
  }
}

async function seedRaceOccurrences() {
  const allRaces = await storage.getRaces({ limit: 10000 });
  const occurrences: InsertRaceOccurrence[] = [];

  for (const race of allRaces) {
    const dateParts = race.date.split("-");
    const year = parseInt(dateParts[0]);
    const month = parseInt(dateParts[1]);

    occurrences.push({
      raceId: race.id,
      startDate: race.date,
      startTime: race.startTime,
      year,
      month,
      status: "scheduled",
    });
  }

  await storage.seedRaceOccurrences(occurrences);
  console.log(`Seeded ${occurrences.length} race occurrences`);
}

export async function seedDatabase() {
  console.log("Seeding database...");

  await storage.seedStates(SEED_STATES);
  console.log(`Seeded ${SEED_STATES.length} states`);

  await storage.seedRaces(SEED_RACES);
  console.log(`Seeded ${SEED_RACES.length} races`);

  await storage.seedRoutes(SEED_ROUTES);
  console.log(`Seeded ${SEED_ROUTES.length} routes`);

  await seedCitiesFromData();
  await linkRacesToCities();
  await seedRaceOccurrences();

  await storage.seedSources(SEED_SOURCES);
  console.log(`Seeded ${SEED_SOURCES.length} sources`);

  await storage.seedCollections(SEED_COLLECTIONS);
  console.log(`Seeded ${SEED_COLLECTIONS.length} collections`);

  console.log("Database seeding complete.");
}
